cpuidle_ladder_does_not_depend_on_ACPI
commit 8eecab24ab74a9b565888f62ab172b5993b85784
Author: Len Brown <len.brown@intel.com>
Date:   Wed Mar 7 04:37:53 2007 -0500

    cpuidle: ladder does not depend on ACPI
    
    build fix for CONFIG_ACPI=n
    
    In file included from drivers/cpuidle/governors/ladder.c:21:
    include/acpi/processor.h:88: error: expected specifier-qualifier-list before âacpi_integerâ
    include/acpi/processor.h:106: error: expected specifier-qualifier-list before âacpi_integerâ
    include/acpi/processor.h:168: error: expected specifier-qualifier-list before âacpi_handleâ
    
    Signed-off-by: Len Brown <len.brown@intel.com>