preempt-realtime-debug-sysctl
Folded in:

From leon.woestenberg@gmail.com Mon Mar 24 17:38:54 2008
Date: Fri, 29 Feb 2008 23:11:40 +0100
From: Leon Woestenberg <leon.woestenberg@gmail.com>
To: linux-rt-users@vger.kernel.org, linux-kernel@vger.kernel.org
Cc: Steven Rostedt <rostedt@goodmis.org>
Subject: [PATCH] Fix build,
     missing profile.h include in kernel/sysctl.c (against 2.6.24.3-rt3)

Build fix for kernel/sysctl.c:356: error: 'prof_pid' undeclared here
(not in a function).
The fix is to include <linux/profile.h> which defines prof_pid as external.
Patch is against 2.6.24.3-rt3.

Signed-off-by: Leon Woestenberg <leon@sidebranch.com>