rcutree: Fix v3.4-rc2-rt2 build break
Fix build break of the following types.

linux-rt/kernel/rcutree_plugin.h: In function ‘print_cpu_stall_fast_no_hz’:
linux-rt/kernel/rcutree_plugin.h:2195: error: ‘rcu_idle_gp_timer’ undeclared (first use in this function)
linux-rt/kernel/rcutree_plugin.h:2195: error: (Each undeclared identifier is reported only once
linux-rt/kernel/rcutree_plugin.h:2195: error: for each function it appears in.)

The config combination that causes a build break is

CONFIG_RCU_FAST_NO_HZ
CONFIG_PREEMPT_RT_FULL
CONFIG_RCU_CPU_STALL_INFO

Reorder the various inline functions so RT picks up the correct ones.

Signed-off-by: John Kacur <jkacur@redhat.com>
Cc: Paul McKenney <paulmck@linux.vnet.ibm.com>
Link: http://lkml.kernel.org/r/1334155379-18088-1-git-send-email-jkacur@redhat.com
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>