per_cpu__ppc64_tlb_batch is only for 64 bit
    [ The following text is in the "iso-8859-15" character set. ]
    [ Your display is set for the "iso-8859-1" character set.  ]
    [ Some special characters may be displayed incorrectly. ]

Fix the following compile error for powerpc32:

arch/powerpc/kernel/process.c: In function '__switch_to':
arch/powerpc/kernel/process.c:355: error: 'per_cpu__ppc64_tlb_batch' undeclared (first use in this function)

Not sure what the code actually does, but as it was not there in -rc5,
somebody else might find something ...

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>