cpuidle_build_fix_cpuidle_vs_ipw2100_module
commit 0157896199e2b0e65b5be1d423aded91634f2861
Author: Len Brown <len.brown@intel.com>
Date:   Thu May 31 22:51:43 2007 -0400

    cpuidle: build fix - cpuidle vs ipw2100 module
    
    ERROR: "acpi_set_cstate_limit" [drivers/net/wireless/ipw2100.ko] undefined!
    
    Signed-off-by: Len Brown <len.brown@intel.com>