remove duplicate save_stack_trace
    [ The following text is in the "iso-8859-15" character set. ]
    [ Your display is set for the "ANSI_X3.4-1968" character set.  ]
    [ Some characters may be displayed incorrectly. ]

Building the kernel with rt-preempt on MPC5121e, I get this one:

arch/powerpc/kernel/stacktrace.o: In function `save_stack_trace':
arch/powerpc/kernel/stacktrace.c:50: multiple definition of `save_stack_trace'
arch/powerpc/kernel/setup_32.o:arch/powerpc/kernel/setup_32.c:328: first defined here

Looks like somebody forgot to remove this in setup_32.c; setup_64.c has
it removed.

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>