timer.c: fix build fail for ! RT_FULL
The patch "timer-handle-idle-trylock-in-get-next-timer-irq.patch"
introduces a use of rt_spin_unlock outside of the RT_FULL, but
since we have:

 #ifdef CONFIG_PREEMPT_RT_FULL
 # include <linux/spinlock_rt.h>
 #else /* PREEMPT_RT_FULL */

we will not get the definition for !RT_FULL and instead see:

kernel/timer.c: In function ‘get_next_timer_interrupt’:
kernel/timer.c:1407: error: implicit declaration of function ‘rt_spin_unlock’
make[2]: *** [kernel/timer.o] Error 1

Extend the ifdef usage to cover the unlock case too.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>